Traceback (most recent call last):
  File "/usr/share/miniconda/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Cleaning up directories after dowloading from MAST
for file in download_tab['Local Path']:
    os.rename(file, os.path.basename(file))
        
shutil.rmtree('mastDownload')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[3], line 3[0m
[1;32m      1[0m [38;5;66;03m# Cleaning up directories after dowloading from MAST[39;00m
[1;32m      2[0m [38;5;28;01mfor[39;00m file [38;5;129;01min[39;00m download_tab[[38;5;124m'[39m[38;5;124mLocal Path[39m[38;5;124m'[39m]:
[0;32m----> 3[0m     [43mos[49m[38;5;241;43m.[39;49m[43mrename[49m[43m([49m[43mfile[49m[43m,[49m[43m [49m[43mos[49m[38;5;241;43m.[39;49m[43mpath[49m[38;5;241;43m.[39;49m[43mbasename[49m[43m([49m[43mfile[49m[43m)[49m[43m)[49m
[1;32m      5[0m shutil[38;5;241m.[39mrmtree([38;5;124m'[39m[38;5;124mmastDownload[39m[38;5;124m'[39m)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: './mastDownload/HST/ib1f19laq/ib1f19laq_flt.fits' -> 'ib1f19laq_flt.fits'
FileNotFoundError: [Errno 2] No such file or directory: './mastDownload/HST/ib1f19laq/ib1f19laq_flt.fits' -> 'ib1f19laq_flt.fits'

